'use strict';

/* The round trip: every indicator the GENERATOR put into the index must be
   found by the PAGE's own extract-and-match path when pasted back as text.

   This is the direct test of the failure the architecture exists to prevent.
   The generator normalises indicators into the index; the browser normalises
   pasted text before matching. If those ever disagreed, by a lowercase, a
   refang, a stripped port or a trailing dot, the lookup would return nothing
   and present as a clean bill of health. Unit tests on either side alone cannot
   catch that, because each would be self-consistent.

   It runs against the REAL committed index, so it also fails if the index is
   ever generated by something other than the shared classifier. */

var test = require('node:test');
var assert = require('node:assert');
var path = require('node:path');
var fs = require('node:fs');
var C = require('../../../assets/js/ioc-classify.js');

var idx = JSON.parse(fs.readFileSync(
  path.join(__dirname, '..', '..', '..', 'assets', 'data', 'ioc-index.json'), 'utf8'));

test('the real index is not empty', function () {
  assert.ok(Object.keys(idx.indicators).length > 500,
    'expected 500+ indicators, got ' + Object.keys(idx.indicators).length);
});

test('every indexed indicator survives a paste round trip', function () {
  var keys = Object.keys(idx.indicators);
  var missed = [];
  keys.forEach(function (key) {
    var value = key.slice(key.indexOf(':') + 1);
    // Paste it the way a human would: surrounded by prose and punctuation.
    var found = C.extract('saw ' + value + ' in the logs.');
    if (!found.some(function (f) { return f.type + ':' + f.value === key; })) {
      missed.push(key);
    }
  });
  assert.deepEqual(missed.slice(0, 10), [],
    missed.length + ' of ' + keys.length + ' indexed indicators cannot be found by ' +
    "the page's own extractor. That is a normalisation drift and it would present " +
    'to a defender as a clean bill of health.');
});

test('a defanged paste of an indexed domain still matches', function () {
  var key = Object.keys(idx.indicators).filter(function (k) {
    return k.indexOf('domain:') === 0;
  })[0];
  assert.ok(key, 'index should contain at least one domain');
  var value = key.slice('domain:'.length);
  var found = C.extract('contacted ' + value.replace(/\./g, '[.]'));
  assert.ok(found.some(function (f) { return 'domain:' + f.value === key; }),
    'a defanged paste of ' + value + ' must still match');
});

test('an uppercase paste of an indexed hash still matches', function () {
  var key = Object.keys(idx.indicators).filter(function (k) {
    return k.indexOf('sha256:') === 0;
  })[0];
  assert.ok(key, 'index should contain at least one sha256');
  var value = key.slice('sha256:'.length);
  var found = C.extract('hash ' + value.toUpperCase());
  assert.ok(found.some(function (f) { return 'sha256:' + f.value === key; }),
    'an uppercase paste must still match');
});

test('no embargoed campaign appears anywhere in the committed index', function () {
  // The campaigns held for disclosure as of 2026-08-20. This is a safety
  // assertion against the real artefact, not a unit test of the generator.
  // 192-3-1-116 (MultiVector) was released 2026-08-20: CNCERT/CC confirmed action
  // on all three of its reports, and its 30-day hold elapsed.
  var held = /13-140-145-210|157-180-101-47/;
  var badReports = Object.keys(idx.reports).filter(function (s) { return held.test(s); });
  assert.deepEqual(badReports, [], 'embargoed campaign in the reports table');
  var badHits = [];
  Object.keys(idx.indicators).forEach(function (k) {
    idx.indicators[k].forEach(function (h) {
      if (held.test(h.report)) badHits.push(k + ' -> ' + h.report);
    });
  });
  assert.deepEqual(badHits.slice(0, 5), [], 'indicator pointing at an embargoed campaign');
});
