'use strict';

/* Builds the per-feed viewer manifest for /ioc-feeds/<slug>/.

   Pure: takes parsed feeds plus resolved publication status, returns the manifest
   and its YAML text. All file I/O lives in generate-ioc-tables.js so this is
   testable without a repo on disk.

   Two properties are load-bearing.

   ONLY PUBLISHED FEEDS GET A PAGE. Three campaigns are under disclosure embargo:
   live at their URL for the people in the loop, absent from every listing. Their
   raw JSON stays exactly where it is, deliberately, but they gain no new rendered
   surface here. Status comes from lib/catalog-status.js, which requires the
   catalog entry and the report front matter to agree and FAILS on a disagreement
   rather than guessing. Inventing a third list is how the third list eventually
   disagrees with the other two, and the direction it fails is a leak.

   THE NOT-TYPED COUNT TRAVELS WITH THE ROWS. A feed carries values the extractor
   cannot type by pattern, command names, JARM fingerprints, free-text behavioural
   notes. The page states how many rather than showing a table that looks complete.
   "22 indicators" and "22 indicators we could type" must not look alike. */

var X = require('./ioc-table-extract.js');

/* TWO derivations, deliberately, because the site already has one and it cannot
   be changed without breaking the search index.

   `keyOf` is the site-wide convention: strip `-iocs.json` wherever it appears.
   That is exactly what the listing page's Liquid does (`remove: '-iocs.json'`)
   and what generate-ioc-index.js keys its reports by. 27 of the 57 feeds are
   named `<name>.json` with no `-iocs`, so for those the key KEEPS its `.json`
   suffix. That looks wrong and is not: changing it would desynchronise every
   card's data-slug from the search index that narrows those cards.

   `slugOf` is the page URL, which must be clean: a directory named
   `AdvancedRouterScanner.json` would sit at the same path as the feed file of
   that name and the build would collide.

   The two are reconciled by the manifest CARRYING the URL rather than anyone
   re-deriving it. The listing looks up `site.data.ioc_tables[islug].page_url`
   with the slug it already has, and the stub carries its own key in front
   matter. No second rule exists in Liquid, so no second rule can drift. */
function keyOf(file) {
  return String(file).split('-iocs.json').join('');
}

function slugOf(file) {
  return String(file).replace(/\.json$/i, '').replace(/-iocs$/i, '');
}

function esc(s) {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')
    .replace(/\n/g, ' ').replace(/\r/g, '') + '"';
}

/* feeds: { 'x-iocs.json': parsedJson }. status: { file -> published|embargoed|unknown }.
   meta:   { file -> catalog entry }. */
function build(feeds, status, meta) {
  var out = {}, problems = [], skipped = { embargoed: 0, unknown: 0, empty: 0 };
  var bySlug = {};

  Object.keys(feeds).sort().forEach(function (file) {
    var st = (status || {})[file] || 'unknown';
    if (st !== 'published') { skipped[st === 'embargoed' ? 'embargoed' : 'unknown']++; return; }

    var slug = slugOf(file);
    var key = keyOf(file);
    if (bySlug[slug]) {
      problems.push('two feeds derive the same page slug "' + slug + '": ' +
        bySlug[slug] + ' and ' + file);
      return;
    }
    if (out[key]) {
      problems.push('two feeds derive the same manifest key "' + key + '": ' +
        file + ' collides with an earlier feed');
      return;
    }
    bySlug[slug] = file;

    var s = X.summarise(feeds[file]);
    if (!s.rows.length) { skipped.empty++; return; }

    var counts = {};
    s.rows.forEach(function (r) { counts[r.type] = (counts[r.type] || 0) + 1; });

    var m = (meta || {})[file] || {};
    out[key] = {
      slug: slug,
      page_url: '/ioc-feeds/' + slug + '/',
      title: m.title || slug,
      date: m.date || null,
      severity: m.severity || null,
      feed_url: m.ioc_url || ('/ioc-feeds/' + file),
      report_url: m.report_url || null,
      detection_url: m.detection_url || null,
      total: s.rows.length,
      untyped: s.untyped,
      counts: counts,
      rows: s.rows
    };
  });

  return { tables: out, problems: problems, skipped: skipped };
}

function toYaml(tables) {
  var lines = ['# Auto-generated by tools/report-tooling/generate-ioc-tables.js.',
               '# Do NOT edit by hand. Re-run the generator to refresh.',
               '# Embargoed feeds are deliberately absent: they keep their raw JSON',
               '# and gain no rendered page. See lib/ioc-tables.js.'];
  Object.keys(tables).sort().forEach(function (slug) {
    var t = tables[slug];
    lines.push(esc(slug) + ':');
    lines.push('  slug: ' + esc(t.slug));
    lines.push('  page_url: ' + esc(t.page_url));
    lines.push('  title: ' + esc(t.title));
    lines.push('  date: ' + (t.date ? esc(t.date) : 'null'));
    lines.push('  severity: ' + (t.severity ? esc(t.severity) : 'null'));
    lines.push('  feed_url: ' + esc(t.feed_url));
    lines.push('  report_url: ' + (t.report_url ? esc(t.report_url) : 'null'));
    lines.push('  detection_url: ' + (t.detection_url ? esc(t.detection_url) : 'null'));
    lines.push('  total: ' + t.total);
    lines.push('  untyped: ' + t.untyped);
    lines.push('  counts:');
    Object.keys(t.counts).sort().forEach(function (k) {
      lines.push('    ' + k + ': ' + t.counts[k]);
    });
    lines.push('  rows:');
    t.rows.forEach(function (r) {
      lines.push('    - type: ' + esc(r.type));
      lines.push('      value: ' + esc(r.value));
      lines.push('      context: ' + (r.context ? esc(r.context) : 'null'));
    });
  });
  return lines.join('\n') + '\n';
}

/* The stub page. Deliberately minimal: the layout does the rendering, and the
   only thing the stub must carry is the manifest key, so no Liquid rule has to
   re-derive a slug the generator already knows. */
function stub(key, t) {
  return [
    '---',
    'title: ' + esc(t.title + ' — Indicators'),
    'layout: ioc-table',
    'permalink: ' + t.page_url,
    'ioc_slug: ' + esc(key),
    'hide: true',
    '---',
    ''
  ].join('\n');
}

module.exports = { build: build, toYaml: toYaml, stub: stub,
                   slugOf: slugOf, keyOf: keyOf };
